-- Your SQL goes here
CREATE TABLE IF NOT EXISTS RECEIPTS (
    ID VARCHAR (36) PRIMARY KEY,
    RECEIPT_NO VARCHAR (36),
    AMOUNT NUMERIC,
    LOCATION TEXT,
    IMAGE_URI TEXT,
    REWARDS NUMERIC,
    REMARK TEXT,
    STATUS VARCHAR (36),
    CREATED_AT timestamp NOT NULL default current_timestamp,
    CREATED_BY VARCHAR (36),
    UPDATED_BY VARCHAR (36) 
)
