-- Your SQL goes here
CREATE TABLE IF NOT EXISTS MERCHANTS (
    ID VARCHAR (36) PRIMARY KEY,
    MERCHANT_NAME VARCHAR (50) UNIQUE,
    SHORTNAME VARCHAR (50),
    CREATED_AT TIMESTAMP NOT NULL default current_timestamp,
    UPDATED_AT TIMESTAMP,
    CREATED_BY VARCHAR (36)
)
