-- Your SQL goes here
CREATE TABLE IF NOT EXISTS APIACC (
    ID VARCHAR (36) PRIMARY KEY,
    APIKEY VARCHAR (56),
    APISEC TEXT,
    IS_ACTIVE BOOLEAN NOT NULL default TRUE,
    CREATED_AT TIMESTAMP NOT NULL default current_timestamp,
    UPDATED_AT TIMESTAMP,
    UPDATED_BY VARCHAR (36)
)
