-- Your SQL goes here
CREATE TABLE IF NOT EXISTS TRXARCHIVE (
    ID VARCHAR (36) PRIMARY KEY,
    BLOCK NUMERIC,
    HASH VARCHAR (66),
    SENDER VARCHAR (48),
    DESTINATION VARCHAR (48),
    AMOUNT NUMERIC,
    FEE  NUMERIC,
    MEMO TEXT,
    CREATED_AT timestamp NOT NULL default current_timestamp,
    CREATED_BY VARCHAR (36),
    UPDATED_BY VARCHAR (36) 
)
