-- Your SQL goes here
CREATE TABLE IF NOT EXISTS BRANCHES (
    ID VARCHAR (36) PRIMARY KEY,
    MERCHANTS_ID VARCHAR (36),
    BRANCHES_NAME VARCHAR (50) UNIQUE,
    ADDRESS TEXT,
    REWARD_RATES NUMERIC,
    ASSET_CODE VARCHAR (4),
    MINIMUM_SPEND NUMERIC,
    APPROVAL_CODE VARCHAR (6),
    LOGO_URI    TEXT,
    IS_ACTIVE BOOLEAN NOT NULL default TRUE,
    CREATED_AT TIMESTAMP NOT NULL default current_timestamp,
    UPDATED_AT TIMESTAMP,
    CREATED_BY VARCHAR (36),
    GRANTED_FOR VARCHAR (36)
)
